version: 2.0

general:
  branches:
    only:
      - master

defaults: &defaults
  working_directory: ~/sphinx

jobs:
  "html":
    docker:
      - image: testthedocs/ablog
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
              pwd
              ls -la
              ablog build -s content -b html content -w content/_build/html

      - persist_to_workspace:
          root: ~/sphinx/content
          paths:
            - _build/html

  "deploy site":
    docker:
      - image: testthedocs/ttd-zipcurl
        #<<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sphinx/html
      - run:
          command: |
              pwd
              ls -la /root
              .circleci/deploy.sh

workflows:
  version: 2
  btd:
    jobs:
      - "html"
      - "deploy site":
          requires:
             - "html"
